version: '3.8'

services:

  database:
    container_name: schedulesql
    image: vaggm/schedulesql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "172.17.0.1", "-uvaggm", "-ppass"]
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    container_name: scheduleapp
    image: vaggm/scheduleapp
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
        